layout_spectrum: 0.2562724
color:
  saturation: 0.3637447
  lightness: 0.2795699
  brandStrength: 0.672043
  brandColors:
    - '#090909'
    - '#8E6A48'
    - '#FAFFFE'
    - '#DA4936'
    - '#999D9E'
  rhythmicContrast: 0.9767025
typography_spectrum: 0.2634408
name: Stuff Zack Thinks
