name: Stuff Zack Thinks
favicon: null
layout_spectrum: 0.49653
typography_spectrum: 0.2634408
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#8E6A48'
    - '#FAFFFE'
    - '#DA4936'
    - '#999D9E'
  brandStrength: 0.672043
  lightness: 0.2795699
  saturation: 0.3637447
  rhythmicContrast: 0.9767025
purpose: []
